// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WifiWatch.Data;

#nullable disable

namespace WifiWatch.Data.Migrations
{
    [DbContext(typeof(WifiDbContext))]
    partial class WifiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity(
                "WifiWatch.Data.Models.MinuteSample",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("Band").HasColumnType("TEXT");

                    b.Property<int?>("Channel").HasColumnType("INTEGER");

                    b.Property<double?>("DnsMilliseconds").HasColumnType("REAL");

                    b.Property<double?>("InternetJitterMilliseconds").HasColumnType("REAL");

                    b.Property<double>("InternetLossPercent").HasColumnType("REAL");

                    b.Property<double?>("InternetPingMilliseconds").HasColumnType("REAL");

                    b.Property<string>("Link").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("MinuteUtc").HasColumnType("TEXT");

                    b.Property<int?>("ReceiveRateMbps").HasColumnType("INTEGER");

                    b.Property<double?>("ReferenceDnsMilliseconds").HasColumnType("REAL");

                    b.Property<double?>("RouterJitterMilliseconds").HasColumnType("REAL");

                    b.Property<double>("RouterLossPercent").HasColumnType("REAL");

                    b.Property<double?>("RouterPingMilliseconds").HasColumnType("REAL");

                    b.Property<int?>("Rssi").HasColumnType("INTEGER");

                    b.Property<string>("Ssid").HasColumnType("TEXT");

                    b.Property<int?>("TransmitRateMbps").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MinuteUtc");

                    b.ToTable("MinuteSamples");
                }
            );

            modelBuilder.Entity(
                "WifiWatch.Data.Models.NeighborSample",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("Bssid").IsRequired().HasColumnType("TEXT");

                    b.Property<int>("Channel").HasColumnType("INTEGER");

                    b.Property<int?>("ChannelUtilizationPercent").HasColumnType("INTEGER");

                    b.Property<bool>("IsOwn").HasColumnType("INTEGER");

                    b.Property<DateTime>("ScanUtc").HasColumnType("TEXT");

                    b.Property<int>("SignalPercent").HasColumnType("INTEGER");

                    b.Property<string>("Ssid").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanUtc");

                    b.ToTable("NeighborSamples");
                }
            );

            modelBuilder.Entity(
                "WifiWatch.Data.Models.SpeedTest",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<double>("DownloadMbps").HasColumnType("REAL");

                    b.Property<double?>("DownloadPingMilliseconds").HasColumnType("REAL");

                    b.Property<string>("Grade").IsRequired().HasColumnType("TEXT");

                    b.Property<double?>("IdlePingMilliseconds").HasColumnType("REAL");

                    b.Property<string>("Link").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("TestedAtUtc").HasColumnType("TEXT");

                    b.Property<double>("UploadMbps").HasColumnType("REAL");

                    b.Property<double?>("UploadPingMilliseconds").HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TestedAtUtc");

                    b.ToTable("SpeedTests");
                }
            );

            modelBuilder.Entity(
                "WifiWatch.Data.Models.WifiEvent",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("Details").HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc").HasColumnType("TEXT");

                    b.Property<bool>("IsAlert").HasColumnType("INTEGER");

                    b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");

                    b.Property<string>("Message").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc").HasColumnType("TEXT");

                    b.Property<string>("Scope").HasColumnType("TEXT");

                    b.Property<string>("Severity").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("Events");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
