// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WifiWatch.Data;

#nullable disable

namespace WifiWatch.Data.Migrations
{
    [DbContext(typeof(WifiDbContext))]
    [Migration("20261005214758_AddNeighborSamples")]
    partial class AddNeighborSamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity(
                "WifiWatch.Data.MinuteSample",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("Band").HasColumnType("TEXT");

                    b.Property<int?>("Channel").HasColumnType("INTEGER");

                    b.Property<double?>("InternetJitterMilliseconds").HasColumnType("REAL");

                    b.Property<double>("InternetLossPercent").HasColumnType("REAL");

                    b.Property<double?>("InternetPingMilliseconds").HasColumnType("REAL");

                    b.Property<string>("Link").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("MinuteUtc").HasColumnType("TEXT");

                    b.Property<int?>("ReceiveRateMbps").HasColumnType("INTEGER");

                    b.Property<double?>("RouterJitterMilliseconds").HasColumnType("REAL");

                    b.Property<double>("RouterLossPercent").HasColumnType("REAL");

                    b.Property<double?>("RouterPingMilliseconds").HasColumnType("REAL");

                    b.Property<int?>("Rssi").HasColumnType("INTEGER");

                    b.Property<string>("Ssid").HasColumnType("TEXT");

                    b.Property<int?>("TransmitRateMbps").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MinuteUtc");

                    b.ToTable("MinuteSamples");
                }
            );

            modelBuilder.Entity(
                "WifiWatch.Data.NeighborSample",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("Bssid").IsRequired().HasColumnType("TEXT");

                    b.Property<int>("Channel").HasColumnType("INTEGER");

                    b.Property<int?>("ChannelUtilizationPercent").HasColumnType("INTEGER");

                    b.Property<bool>("IsOwn").HasColumnType("INTEGER");

                    b.Property<DateTime>("ScanUtc").HasColumnType("TEXT");

                    b.Property<int>("SignalPercent").HasColumnType("INTEGER");

                    b.Property<string>("Ssid").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanUtc");

                    b.ToTable("NeighborSamples");
                }
            );

            modelBuilder.Entity(
                "WifiWatch.Data.WifiEvent",
                b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<bool>("IsAlert").HasColumnType("INTEGER");

                    b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");

                    b.Property<string>("Message").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("Events");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
