<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.12" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\WifiWatch.Data\WifiWatch.Data.csproj" />
    </ItemGroup>
</Project>
